project:
  type: website

website:
  title: "Izabela Oliveira"
  description: "Izabela is professor at Universidade Federal de Lavras (UFLA)"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching

  page-footer:
    left: |
      Â© Izabela Oliveira, 2025  
      Made with [Quarto](https://quarto.org/)
    center: |
      <div class="footer-social">
        <a href="https://github.com/izabela-rco1" target="_blank" aria-label="GitHub">
          <i class="bi bi-github"></i>
        </a>
        <a href="https://www.linkedin.com/in/izabela-oliveira-8a424855/" target="_blank" aria-label="LinkedIn">
          <i class="bi bi-linkedin"></i>
        </a>
        <a href="https://scholar.google.com/citations?user=sUPZKeoAAAAJ&hl=pt-BR" target="_blank" aria-label="Google Scholar">
          <i class="ai ai-google-scholar"></i>
        </a>
        <a href="https://orcid.org/0000-0003-3254-2827" target="_blank" aria-label="ORCID">
          <i class="ai ai-orcid"></i>
        </a>
        <a href="http://lattes.cnpq.br/3989787989553183" target="_blank" aria-label="Lattes">
          <i class="ai ai-lattes"></i>
        </a>
      </div>
    right: |
      <a href="mailto:izabela.oliveira@ufla.br" class="btn btn-footer-outline">
        <i class="bi bi-envelope-fill"></i> Contact me
      </a>
  
  twitter-card: true
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    fig-align: center

# ADICIONE ESTAS LINHAS:
filters:
  - academicons